update chart release action to use CR release v1.4.0
helm/chart-releaser-action pull request #106
Opened 2022-03-27 14:54 UTC by cpanato

- update chart release action to use CR release v1.4.0

2022-03-28 13:18 UTC, unguiculus requested changes

2022-03-28 13:18 UTC, unguiculus commented on .github/workflows/test-action.yml
> +        fi
You could use the `--exit-code` flag. The else branch is unnecessary.
```suggestion
        if ! git diff --stat --exit-code; then
          echo 'should be clean'
          exit 1
        fi
```

2022-03-28 13:18 UTC, unguiculus commented on action.yml
> +          echo $install >> $GITHUB_PATH
Always quote variables
```suggestion
          echo $install >> "$GITHUB_PATH"
```

2022-03-28 13:18 UTC, unguiculus commented on action.yml
> +          echo ${{ inputs.install_dir }} >> $GITHUB_PATH
```suggestion
          echo ${{ inputs.install_dir }} >> "$GITHUB_PATH"
```

2022-03-28 17:49 UTC, scottrigby reviewed
Apart from @unguiculus suggestions, this lgtm! Once we merge this and release a new version of the action, we can update https://github.com/helm/charts-repo-actions-demo 😊

IF we want to use helm/charts-repo-actions-demo repo to test this before merging – which we have done in the past – we can do by pointing this PRs branch on your fork and ensure all is well there. Not sure if we need that anymore but it has been helpful in the past

2022-03-29 07:49 UTC, cpanato commented on action.yml
> +          echo ${{ inputs.install_dir }} >> $GITHUB_PATH
thanks for your review @unguiculus

2022-03-29 08:12 UTC, unguiculus approved these changes
LGTM

2022-03-30 08:25 UTC, merged