Add flag `skip-existing` to skip upload if release exists
helm/chart-releaser-action pull request #134
Opened 2023-02-12 18:51 UTC by xunleii

Should probably closes #70 (implements the last comment https://github.com/helm/chart-releaser-action/issues/70#issuecomment-919904216)

2023-02-20 21:33 UTC, szaimen commented
Hi, this should already be possible with https://github.com/helm/chart-releaser/blob/ee26f50ce93ca23920dc1ce93e677665ce65a46e/README.md?plain=1#L156 IIRC...

2023-02-23 08:14 UTC, xunleii commented
Hi, you're right @szaimen, I didn't see this var. 
Personnaly, adding it directly as an action parameter seems better for me to keep consistency between action parameters and CR parameters (like `owner` for `CR_OWNER` or `repo` for `CR_GIT_REPO`). What do you think ?

2023-03-24 11:02 UTC, cpanato commented on action.yml
> +    description: "Skip the packaging option (do your custom packaging before running this action"
```suggestion
    description: "Skip the packaging option (do your custom packaging before running this action)"
```

2023-03-24 11:03 UTC, cpanato requested changes
need a rebase

2023-04-25 13:04 UTC, cpanato approved these changes
lgtm, not against, but we might don't  want to add all possible due to limitation of the github action inputs

2023-04-25 13:04 UTC, merged