Add `--pages-branch` parameter
helm/chart-releaser-action pull request #156
Opened 2023-08-16 01:48 UTC by michalbiesek

Ref:
  helm/chart-releaser@378f527
  helm/chart-releaser@cb0563b

2023-09-04 10:42 UTC, cpanato requested changes
need rebase

and maybe we only set that parameter if the user pass it otherwise we keep the existing behavior, wdyt?

2023-09-04 11:07 UTC, michalbiesek commented
> need rebase

Rebased.

> and maybe we only set that parameter if the user pass it otherwise we keep the existing behavior, wdyt?

I've changed the implementation. Please take a look.

2023-09-04 13:28 UTC, cpanato requested changes

2023-09-04 13:28 UTC, cpanato commented on README.md
> +- `pages_branch`: The GitHub pages branch
```suggestion
- `pages_branch`: Name of the branch to be used to push the index and artifacts. (default to: gh-pages but it is not set in the action it is a default value for the chart-releaser binary)
```

2023-09-04 13:46 UTC, michalbiesek commented on action.yml
> +    description: "The GitHub pages branch"
Done.

2023-09-04 17:02 UTC, michalbiesek commented
> need rebase

Rebased.

2023-09-05 07:10 UTC, merged

2023-09-05 07:10 UTC, cpanato commented
thanks!