Add option to exclude tags
helm/chart-releaser-action pull request #157
Opened 2023-08-17 21:36 UTC by zalsader

The current code for `lookup_latest_tag` finds the latest tag, whether it was generated by helm or not. This option allows excluding a certain pattern of tags. e.g. `v*` to exclude version tags.

2023-09-04 10:41 UTC, cpanato requested changes
thanks!

can you also add this option to the readme?

2023-09-04 10:41 UTC, cpanato commented on action.yml
> +    description: "Exclude tags matching a this glob when looking for latest release"
can you rephrase this sentence, I feel that is not clear enough

2023-09-06 00:39 UTC, zalsader commented
Added

2024-01-17 02:36 UTC, zalsader commented
@cpanato could you please take a look again?

2024-01-20 09:55 UTC, cpanato commented
thanks. Before we merge this, is it possible to show test evidence that it is working? also show the a test that the normal case still works 

thanks

2024-05-08 03:26 UTC, zalsader commented
Closing because I no longer have access to the original repository.

2024-05-08 03:26 UTC, closed without merging