Bump actions/checkout from v3 to v4 in example action in README.md
helm/chart-releaser-action pull request #206
Opened 2024-08-01 14:30 UTC by zckv

Hello 👋 

Simple change in the readme.md, to reflect the deprecation of actions/checkout@v3
The change was made in the test_action in a917fd1, so I assume it works well.

2024-12-14 17:58 UTC, dnskr approved these changes

2024-12-14 18:16 UTC, dnskr requested changes
@zckv Could you please fix a typo from `exemple` to `example` in the PR title and commit message?

2024-12-19 08:27 UTC, zckv commented
Done, thanks for pointing it out :)

2024-12-19 18:10 UTC, dnskr commented
I think you also need to sign you commit to pass DCO: https://github.com/helm/chart-releaser-action/pull/206/checks?check_run_id=34641574402

2024-12-20 21:54 UTC, dnskr approved these changes

2025-01-20 11:01 UTC, cpanato approved these changes

2025-01-20 11:02 UTC, merged