Fix charts_dir depth
helm/chart-releaser-action pull request #62
Opened 2020-11-08 23:35 UTC by aabouzaid

A tiny fix to make charts_dir works again with the current working dir.
Related to: #61

2021-02-19 15:34 UTC, unguiculus requested changes
While this might fix it for the root dir, it breaks it if charts are in the default `charts` dir.

2021-03-07 13:50 UTC, monotek commented
This should do the drick:

```
depth=$(( $(tr "/" "\n" <<< "$charts_dir" | sed '/^\(\.\)*$/d' | wc -l) + 1 ))
``` 

Deletes empty lines which should fix the absolute path problem and deletes lines which only contain ".".

2021-03-07 13:55 UTC, monotek requested changes

2021-03-07 13:55 UTC, monotek commented on cr.sh
> +    local depth=$(( $(tr "/" "\n" <<< "$charts_dir" | wc -l) ))
This should do the drick:

```
depth=$(( $(tr "/" "\n" <<< "$charts_dir" | sed '/^\(\.\)*$/d' | wc -l) + 1 ))
```

2021-03-07 13:56 UTC, monotek commented
@aabouzaid
could you update your pr please?

2021-06-28 19:26 UTC, unguiculus commented
Superseded by #83

2021-06-28 19:26 UTC, closed without merging